DROP VIEW IF EXISTS VistaCascade2;
DROP VIEW IF EXISTS VistaCascade;
DROP VIEW IF EXISTS VistaLocal2;
DROP VIEW IF EXISTS VistaLocal;
DROP VIEW IF EXISTS vistaPunto10_2;
DROP VIEW IF EXISTS vistaPunto10;